<?xml version="1.0" encoding="UTF-8"?>
<!--Version number of this xml-file : V120 -->
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Frank Van Der Wal (Philips Components Optical) -->
<!-- Number conversions:

    Numbers that are not immediately followed by lower-case b or h are decimal values.
    Numbers immediately followed by lower-case b (xxb) are binary values. Binary values longer than 4 bits are represented as hexadecimal values.
    Numbers or upper case letters immediately followed by lower-case h (xxh) are hexadecimal values.
    When the value of the bit or field is not relevant, x or xx appears in place of a specific value.
    Ranges can be defined by using a dash (e.g. 20h-30h). The values of a range must always be relevant.
     -->
<!DOCTYPE ATAPI [
    <!ELEMENT ATAPI (commands, errors)>
    <!ELEMENT block (selection?, size?, parameter*, block*, repeat?)>
    <!ATTLIST block
    name CDATA #IMPLIED
        hidden (yes | no) #IMPLIED
>
    <!ELEMENT command (block+)>
    <!ATTLIST command
    name CDATA #REQUIRED
        direction (input | none | output) #REQUIRED
        group CDATA #IMPLIED
        timeout CDATA "10"
>
    <!ELEMENT commands (optionsets, command+)>
    <!ELEMENT error EMPTY>
    <!ATTLIST error
    value CDATA #REQUIRED
        description CDATA #REQUIRED
>
    <!ELEMENT errors (error+)>
    <!ELEMENT option EMPTY>
    <!ATTLIST option
    value CDATA #REQUIRED
        description CDATA #REQUIRED
>
    <!ELEMENT optionset (option+)>
    <!ATTLIST optionset
    name CDATA #REQUIRED
>
    <!ELEMENT optionsets (optionset+)>
    <!ELEMENT parameter (option*)>
    <!ELEMENT repeat (size?, block+)>
    <!ATTLIST parameter
    byte CDATA #REQUIRED
        bit CDATA #IMPLIED
        name CDATA #REQUIRED
        default CDATA #IMPLIED
        readonly (yes | no) #IMPLIED
        hidden (yes | no) #IMPLIED
        format (ascii | raw) #IMPLIED
        optionset CDATA #IMPLIED
>
    <!ELEMENT selection EMPTY>
    <!ATTLIST selection
    block CDATA #REQUIRED
        byte CDATA #REQUIRED
        bit CDATA #IMPLIED
        value CDATA #REQUIRED
>
    <!ELEMENT size EMPTY>
    <!ATTLIST size
    fixed CDATA #IMPLIED
        byte CDATA #IMPLIED
        correction CDATA #IMPLIED
        block CDATA #IMPLIED
        multiply CDATA #IMPLIED
>
]>
<ATAPI>
    <commands>
        <optionsets>
            <optionset name="Mode Page Codes">
                <option value="01h" description="Read/Write Error Recovery Mode Page"/>
                <option value="03h" description="MRW Mode Page"/>
                <option value="05h" description="Write Parameter page"/>
                <option value="08h" description="Caching Page"/>
                <option value="0Dh" description="CD Device Parameters Page"/>
                <option value="0Eh" description="CD Audio Control Page"/>
                <option value="1Ah" description="Power Condition Page"/>
                <option value="1Ch" description="Fault/Failure Reporting Page"/>
                <option value="1Dh" description="Time-out &amp; Protect Page"/>
                <option value="2Ah" description="MM Capabilities &amp; Mechanical Status Page"/>
                <option value="3Fh" description="Return all pages"/>
            </optionset>
            <optionset name="Features">
                <option value="0000h" description="Profile List"/>
                <option value="0001h" description="Core"/>
                <option value="0002h" description="Morphing"/>
                <option value="0003h" description="Removable Medium"/>
                <option value="0004h" description="Write Protect"/>
                <option value="0005h-000Fh" description="Reserved"/>
                <option value="0010h" description="Random Readable"/>
                <option value="0011h-001Ch" description="Reserved"/>
                <option value="001Dh" description="Multi-Read"/>
                <option value="001Eh" description="CD Read  The ability to read CD specific structures"/>
                <option value="001Fh" description="DVD Read  The ability to read DVD specific structures"/>
                <option value="0020h" description="Random Writable  Write support for randomly addressed writes"/>
                <option value="0021h" description="Incremental Streaming Writable"/>
                <option value="0022h" description="Sector erasable"/>
                <option value="0023h" description="Formattable"/>
                <option value="0024h" description="Defect Management"/>
                <option value="0025h" description="Write Once"/>
                <option value="0026h" description="Restricted Overwrite"/>
                <option value="0027h" description="CD-RW CAV Write"/>
                <option value="0028h" description="MRW"/>
                <option value="0029h" description="Enhanced Defect Reporting"/>
                <option value="002Ah" description="DVD+RW"/>
                <option value="002Bh" description="DVD+R"/>
                <option value="002Ch" description="Rigid Restricted Overwrite"/>
                <option value="002Dh" description="CD Track at Once"/>
                <option value="002Eh" description="CD Mastering"/>
                <option value="002Fh" description="DVD-R/-RW Write"/>
                <option value="0030h" description="DDCD Read"/>
                <option value="0031h" description="DDCD-R Write"/>
                <option value="0032h" description="DDCD-RW Write"/>
                <option value="0033h" description="DVD-R/-RW Write Feature Descriptor"/>
                <option value="0034h-0036h" description="Reserved"/>
                <option value="0037h" description="CD-RW Media Write Support"/>
                <option value="0038h" description="BD-R Pseudo-Overwrite (POW)"/>
                <option value="0039h-003Ah" description="Reserved"/>
                <option value="003Bh" description="DVD+R Double Layer"/>
                <option value="003Ch-003Fh" description="Reserved"/>
                <option value="0040h" description="BD Read"/>
                <option value="0041h" description="BD Write"/>
                <option value="0043h" description="BD-RE"/>
                <option value="0044h-00FFh" description="Reserved"/>
                <option value="0100h" description="Power Management"/>
                <option value="0101h" description="S.M.A.R.T."/>
                <option value="0102h" description="Embedded Changer"/>
                <option value="0103h" description="CD Audio analog play"/>
                <option value="0104h" description="Microcode Upgrade"/>
                <option value="0105h" description="Timeout"/>
                <option value="0106h" description="DVD CSS"/>
                <option value="0107h" description="Real Time Streaming"/>
                <option value="0108h" description="Logical Unit serial number"/>
                <option value="0109h" description="Reserved"/>
                <option value="010Ah" description="Disc Control Blocks"/>
                <option value="010Bh" description="DVD CPRM"/>
                <option value="010Ch" description="Firmware Date"/>
                <option value="010Dh" description="Advanced Access Content System"/>
                <option value="010Eh-010Fh" description="Reserved"/>
                <option value="0110h" description="Video Content Protection System"/>
                <option value="0111h-011Fh" description="Reserved"/>
                <option value="0120h" description="BD Content Protection System"/>
                <option value="0121h-FEFFh" description="Reserved"/>
                <option value="FF00h-FFFFh" description="Vendor Specific"/>
            </optionset>
            <optionset name="FormatTypes">
                <option value="00h" description="Default Format"/>
                <option value="01h" description="Spare Area Expansion"/>
                <option value="04h" description="Zone Reformat"/>
                <option value="05h" description="Zone Format"/>
                <option value="10h" description="CD/DVD-RW Full Format"/>
                <option value="11h" description="CD/DVD-RW Grow Session"/>
                <option value="12h" description="CD/DVD-RW Add Session"/>
                <option value="13h" description="DVD-RW Quick Grow the last Session"/>
                <option value="14h" description="DVD-RW Quick Add Session"/>
                <option value="15h" description="DVD-RW Quick"/>
                <option value="24h" description="MRW Full Format"/>
                <option value="26h" description="DVD+RW Basic Format"/>
                <option value="30h" description="Format with Spare Area"/>
                <option value="31h" description="Format without Spare Area"/>
                <option value="32h" description="Format BD-R"/>
            </optionset>
            <optionset name="Profiles">
                <option value="0000h" description="Reserved"/>
                <option value="0001h" description="Non-removable disk"/>
                <option value="0002h" description="Removable disk"/>
                <option value="0003h" description="MO Erasable"/>
                <option value="0004h" description="Optical Write Once"/>
                <option value="0005h" description="AS-MO"/>
                <option value="0006h-0007h" description="Reserved"/>
                <option value="0008h" description="CD-ROM"/>
                <option value="0009h" description="CD-R"/>
                <option value="000Ah" description="CD-RW"/>
                <option value="000Bh-000Fh" description="Reserved"/>
                <option value="0010h" description="DVD-ROM"/>
                <option value="0011h" description="DVD-R Sequential Recording"/>
                <option value="0012h" description="DVD-RAM"/>
                <option value="0013h" description="DVD-RW Restricted Overwrite"/>
                <option value="0014h" description="DVD-RW Sequential Recording"/>
                <option value="0015h" description="DVD-R Dual Layer Sequential Recording"/>
                <option value="0016h" description="DVD-R Dual Layer Jump Recording"/>
                <option value="0017h-0019h" description="Reserved"/>
                <option value="001Ah" description="DVD+RW"/>
                <option value="001Bh" description="DVD+R"/>
                <option value="001Ch-001Fh" description="Reserved"/>
                <option value="0020h" description="DDCD-ROM"/>
                <option value="0021h" description="DDCD-R"/>
                <option value="0022h" description="DDCD-RW"/>
                <option value="0023h-002Ah" description="Reserved"/>
                <option value="002Bh" description="DVD+R Dual Layer"/>
                <option value="002Ch-003Fh" description="Reserved"/>
                <option value="0040h" description="BD-ROM"/>
                <option value="0041h" description="BD-R Sequential Recording (SRM)"/>
                <option value="0042h" description="BD-R Random Recording (RRM)"/>
                <option value="0043h" description="BD-RE"/>
                <option value="0044h-FFFEh" description="Reserved"/>
                <option value="FFFFh" description="Logical Units Not Conforming to a Standard Profile"/>
            </optionset>
            <optionset name="Physical Interface Standard">
                <option value="00000000h" description="Unspecified"/>
                <option value="00000001h" description="SCSI Family"/>
                <option value="00000002h" description="ATAPI"/>
                <option value="00000003h" description="IEEE 1394 - 1995"/>
                <option value="00000004h" description="IEEE 1394A"/>
                <option value="00000005h" description="Fibre Channel"/>
                <option value="00000006h" description="IEEE 1394B"/>
                <option value="00000007h" description="Serial ATAPI"/>
                <option value="00000008h" description="USB (both 1 and 2)"/>
                <option value="00000009h-0000FFFEh" description="Reserved"/>
                <option value="0000FFFFh" description="Vendor Unique"/>
                <option value="00010000h-0001FFFFh" description="Defined by INCITS"/>
                <option value="00020000h-0002FFFFh" description="Defined by SFF"/>
                <option value="00030000h-0003FFFFh" description="Defined by IEEE"/>
                <option value="00040000h-FFFFFFFFh" description="Reserved"/>
            </optionset>
            <optionset name="CDDA Output Port Channel Selection Codes">
                <option value="0000b" description="Output port muted"/>
                <option value="0001b" description="Connect audio channel 0 to this output port"/>
                <option value="0010b" description="Connect audio channel 1 to this output port"/>
                <option value="0011b" description="Connect audio channel 0 and audio channel 1 to this output port"/>
                <option value="0100b" description="Connect audio channel 2 to this output port"/>
                <option value="1000b" description="Connect audio channel 3 to this output port"/>
            </optionset>
            <optionset name="Attenuation Levels for Audio">
                <option value="FFh" description="0db (On)"/>
                <option value="F0h" description="-0.52"/>
                <option value="E0h" description="-1.12"/>
                <option value="C0h" description="-2.45"/>
                <option value="80h" description="-5.95"/>
                <option value="40h" description="-11.9"/>
                <option value="20h" description="-17.8"/>
                <option value="10h" description="-23.6"/>
                <option value="0Fh" description="-24.1"/>
                <option value="0Eh" description="-24.6"/>
                <option value="0Ch" description="-25.9"/>
                <option value="08h" description="-29.1"/>
                <option value="04h" description="-34.2"/>
                <option value="02h" description="-38.6"/>
                <option value="01h" description="-42.1"/>
                <option value="00h" description="Mute (Off)"/>
            </optionset>
            <optionset name="ReadDVDStructure Format Codes">
                <option value="00h" description="Physical Information in the DVD Lead-in area"/>
                <option value="01h" description="Copyright Information from the DVD Lead-in area"/>
                <option value="02h" description="Disc Key obfuscated by a Bus Key"/>
                <option value="03h" description="Burst Cutting Area information"/>
                <option value="04h" description="Disc Manufacturing Information from the DVD Lead-in area"/>
                <option value="05h" description="Copyright Management information"/>
                <option value="06h" description="Media Identifier protected by a Bus Key"/>
                <option value="07h" description="Media Key Block protected by a Bus Key"/>
                <option value="08h" description="DDS information on DVD-RAM Media"/>
                <option value="09h" description="DVD-RAM Medium Status"/>
                <option value="0Ah" description="DVD-RAM Spare Area Information"/>
                <option value="0Bh" description="DVD-RAM Recording Type Information"/>
                <option value="0Ch" description="DVD-R/-RW RMD in last border-out"/>
                <option value="0Dh" description="Specified RMD field from last recorded border out on DVD-R/-RW"/>
                <option value="0Eh" description="Pre-recorded information from DVD-R/-RW lead-in"/>
                <option value="0Fh" description="DVD-R/-RW Media Identifier"/>
                <option value="10h" description="DVD-R/-RW Physical Format Information"/>
                <option value="11h" description="ADIP Information"/>
                <option value="20h" description="DVD+R Dual Layer Boundary Info"/>
                <option value="21h" description="Shifted Middle Area start Address"/>
                <option value="22h" description="Regular Interval Layer Jump Size"/>
                <option value="23h" description="Manual Layer Jump Address"/>
                <option value="24h" description="Remapping Address"/>
                <option value="30h" description="Disc Control Blocks"/>
                <option value="31h" description="Read MTA ECC Block"/>
                <option value="C0h" description="Write Protection Status"/>
                <option value="C1h" description="Next Writable Address Information"/>
                <option value="FFh" description="Capability list"/>
            </optionset>
            <optionset name="ReadBDStructure Format Codes">
                <option value="00h" description="Disc Information (DI)"/>
                <option value="03h" description="Burst Cutting Area information"/>
                <!-- Todo: remove. Temp option for AV  -->
                <option value="08h" description="Disc Definition Structure (DDS)"/>
                <option value="09h" description="Cartridge Status"/>
                <option value="0Ah" description="Spare Area Information"/>
                <option value="0Fh" description="Timestamp"/>
                <option value="12h" description="Raw Defect List (DFL)"/>
                <option value="13h" description="AACS Volume ID"/>
                <option value="14h" description="AACS Media Serial Number"/>
                <option value="16h" description="AACS Media ID"/>
                <option value="30h" description="Physical Access Control (PAC)"/>
                <option value="C0h" description="Write Protection Status"/>
                <option value="FFh" description="BD Structure List"/>
            </optionset>
            <optionset name="Enabled/Disabled">
                <option value="0b" description="Disabled"/>
                <option value="1b" description="Enabled"/>
            </optionset>
            <optionset name="Support">
                <option value="0b" description="Not supported"/>
                <option value="1b" description="Supported"/>
            </optionset>
            <optionset name="Yes/No">
                <option value="0b" description="No"/>
                <option value="1b" description="Yes"/>
            </optionset>
            <optionset name="On/Off">
                <option value="0b" description="Off"/>
                <option value="1b" description="On"/>
            </optionset>
            <optionset name="AfeSignals">
                <option value="0" description="AFE_FE"/>
                <option value="1" description="AFE_TE"/>
                <option value="2" description="AFE_BHSO"/>
                <option value="3" description="AFE_RP"/>
                <option value="4" description="AFE_SBAD"/>
                <option value="5" description="AFE_CE"/>
                <option value="6" description="AFE_SRFO"/>
            </optionset>
            <optionset name="OPCSamples">
                <option value="0" description="NR_OF_SAMPLES_1"/>
                <option value="1" description="NR_OF_SAMPLES_2"/>
                <option value="2" description="NR_OF_SAMPLES_4"/>
                <option value="3" description="NR_OF_SAMPLES_8"/>
                <option value="4" description="NR_OF_SAMPLES_16"/>
                <option value="5" description="NR_OF_SAMPLES_32"/>
                <option value="6" description="NR_OF_SAMPLES_64"/>
                <option value="7" description="NR_OF_SAMPLES_128"/>
                <option value="8" description="NR_OF_SAMPLES_256"/>
                <option value="9" description="NR_OF_SAMPLES_512"/>
                <option value="10" description="NR_OF_SAMPLES_1024"/>
                <option value="11" description="NR_OF_SAMPLES_ALL"/>
            </optionset>
            <optionset name="OPCAvgSamples">
                <option value="0" description="AVG_SAMPLES_1"/>
                <option value="1" description="AVG_SAMPLES_2"/>
                <option value="2" description="AVG_SAMPLES_4"/>
                <option value="3" description="AVG_SAMPLES_8"/>
                <option value="4" description="AVG_SAMPLES_16"/>
                <option value="5" description="AVG_SAMPLES_32"/>
                <option value="6" description="AVG_SAMPLES_64"/>
                <option value="7" description="AVG_SAMPLES_128"/>
            </optionset>            
            <optionset name="AdjustItems">
                <option value="0" description="SPHER_ABER"/>
                <option value="1" description="FOCUS_OFFSET"/>
                <option value="2" description="TRACKING_OFFSET"/>
                <option value="3" description="TILT"/>
                <option value="4" description="FEBC"/>                
                <option value="6" description="NONE"/>
            </optionset>            
            <optionset name="AdjustCost">
                <option value="0" description="HW_SAMPLED_JITTER"/>
                <option value="1" description="SW_SAMPLED_WOBBLE_BEAT"/>
                <option value="2" description="SW_SAMPLED_RF_P2P"/>                
                <option value="3" description="HW_SAMPLED_TE_P2P"/>                                
            </optionset>    
        </optionsets>       
        <command name="CommandDescriptorBlock" direction="none">
            <block name="cdb">
                <size fixed="12"/>
                <parameter byte="0" name="Operational Code" default="00h" readonly="no"/>
                <parameter byte="1" name="Parameter 1" default="00h" readonly="no"/>
                <parameter byte="2" name="Parameter 2" default="00h" readonly="no"/>
                <parameter byte="3" name="Parameter 3" default="00h" readonly="no"/>
                <parameter byte="4" name="Parameter 4" default="00h" readonly="no"/>
                <parameter byte="5" name="Parameter 5" default="00h" readonly="no"/>
                <parameter byte="6" name="Parameter 6" default="00h" readonly="no"/>
                <parameter byte="7" name="Parameter 7" default="00h" readonly="no"/>
                <parameter byte="8" name="Parameter 8" default="00h" readonly="no"/>
                <parameter byte="9" name="Parameter 9" default="00h" readonly="no"/>
                <parameter byte="10" name="Parameter 10" default="00h" readonly="no"/>
                <parameter byte="11" name="Parameter 11" default="00h" readonly="no"/>
            </block>
        </command>
        <command name="CommandDescriptorBlock6" direction="none">
            <block name="cdb">
                <size fixed="6"/>
                <parameter byte="0" name="Operational Code" default="00h" readonly="no"/>
                <parameter byte="1" name="Parameter 1" default="00h" readonly="no"/>
                <parameter byte="2" name="Parameter 2" default="00h" readonly="no"/>
                <parameter byte="3" name="Parameter 3" default="00h" readonly="no"/>
                <parameter byte="4" name="Parameter 4" default="00h" readonly="no"/>
                <parameter byte="5" name="Parameter 5" default="00h" readonly="no"/>
            </block>
        </command>
        <command name="CommandDescriptorBlock10" direction="none">
            <block name="cdb">
                <size fixed="10"/>
                <parameter byte="0" name="Operational Code" default="00h" readonly="no"/>
                <parameter byte="1" name="Parameter 1" default="00h" readonly="no"/>
                <parameter byte="2" name="Parameter 2" default="00h" readonly="no"/>
                <parameter byte="3" name="Parameter 3" default="00h" readonly="no"/>
                <parameter byte="4" name="Parameter 4" default="00h" readonly="no" />
                <parameter byte="5" name="Parameter 5" default="00h" readonly="no"/>
                <parameter byte="6" name="Parameter 6" default="00h" readonly="no"/>
                <parameter byte="7" name="Parameter 7" default="00h" readonly="no"/>
                <parameter byte="8" name="Parameter 8" default="00h" readonly="no"/>
                <parameter byte="9" name="Parameter 9" default="00h" readonly="no"/>
            </block>
        </command>
        <command name="RezeroUnit" direction="none">
            <block name="cdb">
                <size fixed="6"/>
                <parameter byte="0" name="Operational Code" default="01h" readonly="yes"/>
                <parameter byte="1" name="Parameter 1" default="00h" readonly="no"/>
                <parameter byte="2" name="Parameter 2" default="00h" readonly="no"/>
                <parameter byte="3" name="Parameter 3" default="00h" readonly="no"/>
                <parameter byte="4" name="Parameter 4" default="00h" readonly="no"/>
                <parameter byte="5" name="Parameter 5" default="00h" readonly="no"/>
            </block>
        </command>
        <command name="Blank" direction="none">
            <block name="cdb">
                <size fixed="12"/>
                <parameter byte="0" name="Operational Code" default="A1h" readonly="yes"/>
                <parameter byte="1" bit="4" name="Immediate" optionset="Yes/No"/>
                <parameter byte="1" bit="2-0" name="Blanking Type">
                    <option value="000b" description="Stop a background format"/>
                    <option value="001b" description="Close the track associated with the track number in the CDB"/>
                    <option value="010b" description="Close the last incomplete session or stop a background format and structure for read compatibility"/>
                    <option value="011b" description="Special case close session"/>
                    <option value="101b" description="Close Last Session and Finalize the Disc - special case "/>
                    <option value="110b" description="Close Last Session and Finalize the Disc"/>
                </parameter>
                <parameter byte="2-5" name="Start Address/Track Number"/>
            </block>
        </command>
        <command name="BenQServiceMode" direction="none" group="vendor unique">
            <block name="cdb">
                <size fixed="12"/>
                <parameter byte="0" name="Operational Code" default="FDh" readonly="yes"/>
                <parameter byte="1" name="Service mode">
                    <option value="F1h" description="Enable"/>
                    <option value="F2h" description="Disable"/>
                </parameter>
                <parameter byte="2-5" name="Id" default="BENQ" format="ascii" readonly="yes"/>
                <parameter byte="6-9" name="Signature" format="ascii"/>
            </block>
        </command>
        <command name="CloseTrackSession" direction="none">
            <block name="cdb">
                <size fixed="10"/>
                <parameter byte="0" name="Operational Code" default="5Bh" readonly="yes"/>
                <parameter byte="1" bit="0" name="Immediate" optionset="Yes/No"/>
                <parameter byte="2" bit="2-0" name="Close Function">
                    <option value="000b" description="Stop a Background Format"/>
                    <option value="001b" description="Close Logical Track"/>
                    <option value="010b" description="Close Session or Stop a Background Format"/>
                    <option value="011b" description="Special Case Close Session"/>
                    <option value="100b" description="Close the Open Session and Record an Extended Lead-out"/>
                    <option value="101b" description="Finalize the Disc with a Minimum Recorded Radius"/>
                    <option value="110b" description="Finalize the Disc"/>
                    <option value="111b" description="Reserved"/>
                </parameter>
                <parameter byte="4-5" name="Track Number"/>
            </block>
        </command>
        <command name="Erase10" direction="none">
            <block name="cdb">
                <size fixed="10"/>
                <parameter byte="0" name="Operational Code" default="2Ch" readonly="yes"/>
                <parameter byte="1" bit="2" name="Erase All" optionset="Yes/No"/>
                <parameter byte="1" bit="1" name="Immediate" optionset="Yes/No"/>
                <parameter byte="2-5" name="Logical Block Address"/>
                <parameter byte="7-8" name="Number of Blocks"/>
            </block>
        </command>
        <command name="FormatUnit" direction="output">
            <block name="cdb">
                <size fixed="12"/>
                <parameter byte="0" name="Operational Code" default="04h" readonly="yes"/>
                <parameter byte="1" bit="4" name="FmtData" default="1b">
                    <option value="0b" description="no parameter list"/>
                    <option value="1b" description="parameter list is available"/>
                </parameter>
                <parameter byte="1" bit="3" name="CmpList">
                    <option value="0b" description="parameter list provided is in addition to those already available"/>
                    <option value="1b" description="parameter list is complete"/>
                </parameter>
                <parameter byte="1" bit="2-0" name="Format Code">
                    <option value="001b" description="Other Format Descriptor"/>
                    <option value="111b" description="DDCD-RW / CD-RW Format Descriptor"/>
                </parameter>
                <parameter byte="3-4" name="Interleave Value"/>
            </block>
            <block name="buffer">
                <block name="Format Parameter List">
                    <block name="Format List Header">
                        <size fixed="4"/>
                        <parameter byte="0" name="Reserved"/>
                        <parameter byte="1" bit="7" name="FOV"/>
                        <parameter byte="1" bit="6" name="DPRY"/>